services:
  # POSTGRES DB
  db:
    image: postgres:16-alpine
    container_name: forum_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # BACKEND
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: forum_backend
    restart: unless-stopped
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public"
      NODE_ENV: development
    depends_on:
      db: # Waits for DB service to be "healthy"
        condition: service_healthy  
    volumes:
      - ./apps/backend/src:/app/src
      - ./apps/backend/prisma:/app/prisma
    profiles:
      - fullstack

volumes:
  postgres_data: